# Default values for Odysseia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  environment: minikube
  externalRepo: true
  privateImagesInRepo: false
  tls: true
  pullPolicy: Never
  replicas:
    low: 1
    medium: 2
    high: 4
  initialDelayLiveness: 20
  initialDelayReadiness: 1
  periodSeconds: 20

services:
  backend:
    labels: {
      domain: backend
    }
  sidecar:
    name: "ptolemaios"
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "100m"
  seeder:
    name: "parmenides"
    role: "seeder"
    access: "quiz"
  init:
    name: "periandros"
  odysseiaapi:
    name: "sokrates"
    role: "api"
    access: "quiz"
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "150m"

images:
  tag: 4952f80
  imageRepo: core.harbor.domain:30003/odysseia/
  pullSecret: harbor-images
  sidecar:
    repo: ptolemaios
  init:
    repo: periandros
  odysseiaapi:
    repo: sokrates
  seeder:
    repo: parmenides

envVariables:
  solonService: http://solon-service:5000
  vaultService: http://vault:8200
  elasticService: https://elastic-master:9200
  mqService: queue
  mqPort: 50000
  odysseiaapi:
    port: 5000
  sidecar:
    port: 5001

namespaceOverride: odysseia
