# Default values for Odysseia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  externalRepo: true
  privateImagesInRepo: false
  environment: minikube
  tls: true
  sidecarOverwrite: true
  pullPolicy: Never
  harborPullPolicy: Always
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZUekNDQXplZ0F3SUJBZ0lDQitNd0RRWUpLb1pJaHZjTkFRRUxCUUF3RHpFTk1Bc0dBMVVFQ2hNRWRHVnoKZERBZUZ3MHlNakEyTWpFeE16UTNNRFJhRncwek1qQTJNVGd4TXpRM01EUmFNQTh4RFRBTEJnTlZCQW9UQkhSbApjM1F3Z2dJaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRRGUydTlVZ25jQnlVWksrdTRrCkZnSlRGSSs2Z2JYNjB6ZVA2UVhobTkzRDJQdmlaMklLRUlUS1BPRitJNnkzek4vWXU4enhTWHNDYjhhZXlKbVcKUFdITUt3QjBIQTdVRHh4OEF6V1hEOUt1dzhXVFZXK3hNeHF3M3JaWGtsWmh6QkFqNDJpaWlmZnZrbi96SzY4VgpvcjB0b1pqcFdLdmtRRVdRSEVwdzFZOXFuQXNwdHVQS012NHpPL0U4NkdLL3k4M0RJYWNTOHRjR3ZGbGZpc1RRCmZzTjhGYkVjRWRZS2ZJK2lkYVNzMHVFMjZ5ZUQ5YkVReTRFbWxRNlVLeVo3WDZ4S2UwSDYzY20xNVRhNVkybXcKdXM1VExnK3lneDNkZ1NsTS9xVUdkbFBKRWpMNS8wL2JwNHJ0bkV2UUUxdU9sVkJ5SmtZMEltTktXYnphaGYvawp5TnZSRzg0dUpFN1UraWMyaWpLVDNlSzlKY1hLZGo0ajRvWFFSWFRuQlk1UzZmMGNqbzJ4VnNLdDA1Wi9zd2hrCk11VmZoaG5KQUJFTlc0Q3BGZXBCeGVXQzlOZFJWUzN2VTZXU1FSRGk5SXNtcFdMQ0c4ZE1sTmVGekZ0c2lmVTYKQUVTWXBqdFNkZnNRSkdXbWR5QjdKWk50WUkzcHhpM1dmaytTU0lETmRkOEhOclZPUWNZOEJQMGhmQ0lWa3YwMAptUlZteXFyWTBIRFA3WnFISTNxVk9uZGIzK2l2R2tMMjViODV2NXNWQWcvMFh3WE4xcVFYejFSVHBVSTllTWxVCkRnMFNVYnFzaUZGZElaNmw5d3A5QlFZZmYyYWNhMW5DaTFiTUdFTFdCc0pXU0NUNk9WaXk1Uklxb3NRbkxJODQKU2h3NzNvbTVTUHM1WE9TNm5tMFNSY1ZYUlFJREFRQUJvNEcwTUlHeE1BNEdBMVVkRHdFQi93UUVBd0lIZ0RBZApCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBZ1lJS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQU9CZ05WCkhRNEVCd1FGQVFJREJBWXdZZ1lEVlIwUkJGc3dXWUlJY0dWeWFXdHNaWE9DRVhCbGNtbHJiR1Z6TG05a2VYTnoKWldsaGdoVndaWEpwYTJ4bGN5NXZaSGx6YzJWcFlTNXpkbU9DSTNCbGNtbHJiR1Z6TG05a2VYTnpaV2xoTG5OMgpZeTVqYkhWemRHVnlMbXh2WTJGc01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQmtpVzdCSmdsRGg5YnNpZUVSCnpYS0lzQnlMa2JIeGt2cDVNakdSR3ArMnNuWThKL0dOYmdBdEk2a3dxMkQ1RmYrelU2YnB3YStibk8wYU9xRE8KN2JjSFhxWW9rOElmWGE0VHJGSnArRGxKYU83SXczMGgwTndzK0xodko4bUszS1YrQThLYW5DMXZLanhpY1FRQwp1VUE3TytzMm9nQVBFSHUvZzU1M3N3SkRnK3E1cG0wMkVIRXNOR1Q4eDBBajMvdXNLc3U3UUFWc1ZrOU1UcHFOClptOE5jNTZCRkd3MkFDb2lYODFDY0NJL0t3SVdCTCtmTTJHeWg0UXd2azdnbmdEMHdRL2h6bHAyMlZFTGVDODUKTVVmWlZ4K1ZadGcvaVE3NlNZOFZHQUQ0bTA5eUtJVGxyUS9EaVk4RFF0V0lDRWZMdnZlQ0R4VW5LdndJcUgxRApIbXN2OWZ4cCtVSHpMWGNIYjd5dURabFpFOWZ1OWxQUXhsSHZuNHFqZWE5aEI3clNPanc3alczVnMvTkdEaW41Cjh5Wk1oK1VOOHhiYnlqYndwNjJUd0ZJRGpDNkpadzU4NjRucEdLNU95ZWdQaGNsVXZVU0xZZ1BITjkySzVDb20KOXVuaSt6SXNhdzMwcjZZN1VKSjhNcUo5UGd3WGRmTkFBSlp6L1Nza2JxWWszV0lxaGFQRlEyaWpFdExVUVhCRgpsdlJrajRKQ0V5RE5BUnZ3VVFWbThPQ2l5bXQyL3dXa1FTbyt3THBxK1phcmFqcWc0Zmd2ZGpWMTE2eCtkZGYzCkh2eFpmdTJBQlNKNWV5TG1kMUR0QUZtUU00RWZITE5FazVPaHNVZTdhTGlGckdaOHppM0dXQ3ZqZVJld2RjWHUKRGRwOUtkK1h1YVFxbzRydGRmSXVFTDAvVkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  replicas:
    low: 1
    medium: 2
    high: 4
  initialDelayLiveness: 20
  initialDelayReadiness: 1
  periodSeconds: 20

services:
  backend:
    labels: {
      domain: backend
    }
  perikles:
    name: "perikles"
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "150m"

images:
  imageRepo: core.harbor.domain:30003/odysseia/
  pullSecret: harbor-images
  tag: 4952f80
  odysseiaapi:
    repo: perikles

envVariables:
  odysseiaapi:
      port: 4443
      crdName: perikles-mapping
      TLSFiles: /etc/certs

serviceAccount:
  name: perikles-access-sa

namespaceOverride: odysseia

role:
  name: perikles-api-access

roleBinding:
  name: perikles-api-access-binding