apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "odysseiaapi.uname" . }}"
  namespace: {{ template "namespace" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    env: {{ .Values.config.environment }}
    app: "{{ template "odysseiaapi.uname" . }}"
    {{- range $key, $value := .Values.services.frontend.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ int .Values.config.replicas.low }}
  selector:
    matchLabels:
      app: "{{ template "odysseiaapi.uname" . }}"
  template:
    metadata:
      labels:
        app: {{ template "odysseiaapi.uname" . }}
        release: {{ .Release.Name }}
        version: {{ .Values.images.tag }}
    spec:
      {{- if .Values.config.inClusterHarbor | quote }}
      imagePullSecrets:
        - name: {{ .Values.images.pullSecret}
      {{- end}}
      containers:
        - name: "{{ template "odysseiaapi.uname" . }}"
          {{- if .Values.config.inClusterHarbor | quote }}
          image: {{ .Values.images.harborRepo}}{{ .Values.images.odysseiaapi.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          {{ else }}
          image: {{ .Values.images.odysseiaapi.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          {{- end}}
          env:
            - name: NODE_ENV
              value: {{ .Values.envVariables.nodeEnv }}
          ports:
            - containerPort: {{ .Values.envVariables.odysseiaapi.port }}
          resources:
            requests:
              memory: {{ .Values.services.odysseiaapi.requests.memory }}
              cpu: {{ .Values.services.odysseiaapi.requests.cpu }}
            limits:
              memory: {{.Values.services.odysseiaapi.limits.memory}}
              cpu: {{.Values.services.odysseiaapi.limits.memory}}
