apiVersion: v1
kind: Service
metadata:
  name: solon-service
  namespace: {{ template "solon.namespace" . }}
spec:
  selector:
    app: "{{ template "solon.uname" . }}"
  ports:
    - name: "https"
      port: {{ .Values.envVariables.solon.port }}
      targetPort: {{ .Values.envVariables.solon.port }}
