# Default values for Odysseia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  externalRepo: true
  privateImagesInRepo: false
  environment: minikube
  pullPolicy: Always
  port: 8080
  replicas:
    low: 1
    medium: 2
    high: 4

services:
  docs:
    labels: {
      domain: docs
    }
  openapi:
    name: "ploutarchos"


images:
  imageRepo: core.harbor.domain:30003/odysseia/
  pullSecret: harbor-images
  tag: 1af8792
  odysseiaapi:
    repo: ploutarchos


namespaceOverride: odysseia
