apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "perikles.uname" . }}"
  namespace: {{ template "perikles.namespace" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    env: {{ .Values.config.environment }}
    app: "{{ template "perikles.uname" . }}"
    {{- range $key, $value := .Values.services.backend.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ int .Values.config.replicas.low }}
  selector:
    matchLabels:
      app: "{{ template "perikles.uname" . }}"
  template:
    metadata:
      labels:
        app: {{ template "perikles.uname" . }}
        release: {{ .Release.Name }}
        version: {{ .Values.images.tag }}
      annotations:
        perikles/ssl-access: "solon;vault"
        perikles/ssl-service: "perikles-service"
    spec:
      serviceAccountName: {{ template "perikles.serviceAccountName" . }}
      {{- if .Values.config.externalRepo | quote }}
      imagePullSecrets:
        - name: {{ .Values.images.pullSecret }}
      {{- end}}
      containers:
        - name: "{{ template "perikles.uname" . }}"
          {{- if .Values.config.externalRepo | quote }}
          image: {{ .Values.images.imageRepo}}{{ .Values.images.odysseiaapi.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.harborPullPolicy }}
          {{ else }}
          image: {{ .Values.images.odysseiaapi.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          {{- end}}
          env:
          - name: ENV
            value: {{ .Values.config.environment }}
          - name: TLSENABLED
            value: {{ .Values.config.tls | quote }}
          - name: PORT
            value: {{ .Values.envVariables.odysseiaapi.port | quote }}
          - name: TLS_FILES
            value: {{ .Values.envVariables.odysseiaapi.TLSFiles }}
          - name: CRD_NAME
            value: {{ .Values.envVariables.odysseiaapi.crdName }}
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
            - containerPort: {{ .Values.envVariables.odysseiaapi.port }}
              name: webhook-tcp
          volumeMounts:
            - name: webhook-certs
              mountPath: {{ .Values.envVariables.odysseiaapi.TLSFiles }}
              readOnly: true
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /perikles/v1/ping
              port: {{ .Values.envVariables.odysseiaapi.port }}
            initialDelaySeconds: {{ .Values.config.initialDelayLiveness }}
            periodSeconds: {{ .Values.config.periodSeconds }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /perikles/v1/ping
              port: {{ .Values.envVariables.odysseiaapi.port }}
            initialDelaySeconds: {{ .Values.config.initialDelayReadiness }}
            periodSeconds: {{ .Values.config.readinessSeconds }}
          resources:
            requests:
              memory: {{ .Values.services.perikles.requests.memory }}
              cpu: {{ .Values.services.perikles.requests.cpu }}
            limits:
              memory: {{.Values.services.perikles.limits.memory}}
              cpu: {{.Values.services.perikles.limits.cpu}}
      volumes:
        - name: webhook-certs
          secret:
            secretName: perikles-certs
