apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ template "perikles.namespace" . }}
  name: {{ template "perikles.roleName" $ }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
