apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ template "perikles.namespace" . }}
  name: {{ template "perikles.roleName" $ }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get", "list", "update", "create"]
  - apiGroups: ["apps"] # "" indicates the core API group
    resources: ["deployments"]
    verbs: ["update", "get"]
  - apiGroups: ["odysseia-greek.com"]
    resources: ["servicemapping"]
    verbs: ["get", "list", "create", "update", "delete"]