apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "odysseiaapi.uname" . }}"
  namespace: {{ template "namespace" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    env: {{ .Values.config.environment }}
    app: "{{ template "odysseiaapi.uname" . }}"
    {{- range $key, $value := .Values.services.backend.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ int .Values.config.replicas.medium }}
  selector:
    matchLabels:
      app: "{{ template "odysseiaapi.uname" . }}"
  template:
    metadata:
      labels:
        app: {{ template "odysseiaapi.uname" . }}
        release: {{ .Release.Name }}
        version: {{ .Values.images.tag }}
      annotations:
        odysseia-greek/role: {{ .Values.services.odysseiaapi.role }}
        odysseia-greek/access: {{ .Values.services.odysseiaapi.access }}
    spec:
      serviceAccountName: {{ template "serviceAccountName" . }}
      {{- if .Values.config.privateImagesInRepo | quote }}
      imagePullSecrets:
        - name: {{ .Values.images.pullSecret}}
      {{- end}}
      initContainers:
        - name: "{{ template "init.uname" . }}"
          {{- if .Values.config.externalRepo | quote }}
          image: {{ .Values.images.imageRepo}}{{ .Values.images.init.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          {{ else }}
          image: {{ .Values.images.init.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          {{- end}}
          env:
          - name: ENV
            value: {{ .Values.config.environment }}
          - name: SOLON_SERVICE
            value: {{ .Values.envVariables.solonService }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ELASTIC_ROLE
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['odysseia-greek/role']
          - name: ELASTIC_ACCESS
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['odysseia-greek/access']
      containers:
        - name: "{{ template "sidecar.uname" . }}"
          {{- if .Values.config.externalRepo | quote }}
          image: {{ .Values.images.imageRepo}}{{ .Values.images.sidecar.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          {{ else }}
          image: {{ .Values.images.sidecar.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          {{- end}}
          env:
          - name: VAULT_SERVICE
            value: {{ .Values.envVariables.vaultService }}
          - name: SOLON_SERVICE
            value: {{ .Values.envVariables.solonService }}
          - name: ENV
            value: {{ .Values.config.environment }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          ports:
            - containerPort: {{ .Values.envVariables.sidecar.port }}
          resources:
            requests:
              memory: {{ .Values.services.sidecar.requests.memory }}
              cpu: {{ .Values.services.sidecar.requests.cpu }}
            limits:
              memory: {{.Values.services.sidecar.limits.memory}}
              cpu: {{.Values.services.sidecar.limits.memory}}
        - name: "{{ template "odysseiaapi.uname" . }}"
          {{- if .Values.config.externalRepo | quote }}
          image: {{ .Values.images.imageRepo}}{{ .Values.images.odysseiaapi.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          {{ else }}
          image: {{ .Values.images.odysseiaapi.repo }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          {{- end}}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ENV
              value: {{ .Values.config.environment }}
            - name: TLSENABLED
              value: {{ .Values.config.tls | quote }}
            - name: ELASTIC_SEARCH_SERVICE
              value: {{ .Values.envVariables.elasticService }}
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          ports:
            - containerPort: {{ .Values.envVariables.odysseiaapi.port }}
          livenessProbe:
            httpGet:
              path: /sokrates/v1/health
              port: {{ .Values.envVariables.odysseiaapi.port }}
            initialDelaySeconds: {{ .Values.config.initialDelayLiveness }}
            periodSeconds: {{ .Values.config.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /sokrates/v1/ping
              port: {{ .Values.envVariables.odysseiaapi.port }}
            initialDelaySeconds: {{ .Values.config.initialDelayReadiness }}
            periodSeconds: {{ .Values.config.periodSeconds }}
          resources:
            requests:
              memory: {{ .Values.services.odysseiaapi.requests.memory }}
              cpu: {{ .Values.services.odysseiaapi.requests.cpu }}
            limits:
              memory: {{.Values.services.odysseiaapi.limits.memory}}
              cpu: {{.Values.services.odysseiaapi.limits.memory}}
