apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odysseia-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: odysseia-ingress
spec:
  defaultBackend:
    service:
      name: sokrates
      port:
        number: {{ .Values.envVariables.sokrates.port }}
  rules:
    - host: {{ .Values.config.host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pheidias
                port:
                  number: {{ .Values.envVariables.pheidias.port }}
          - pathType: Prefix
            path: /sokrates/v1
            backend:
              service:
                name: sokrates
                port:
                  number: {{ .Values.envVariables.sokrates.port }}
          - pathType: Prefix
            path: /herodotos/v1
            backend:
              service:
                name: herodotos
                port:
                  number: {{ .Values.envVariables.herodotos.port }}
          - pathType: Prefix
            path: /alexandros/v1
            backend:
              service:
                name: alexandros
                port:
                  number: {{ .Values.envVariables.alexandros.port }}
          - pathType: Prefix
            path: /dionysios/v1
            backend:
              service:
                name: dionysios
                port:
                  number: {{ .Values.envVariables.dionysios.port }}
          - pathType: Prefix
            path: /ploutarchos
            backend:
              service:
                name: ploutarchos
                port:
                  number: {{ .Values.envVariables.ploutarchos.port }}
          - pathType: Prefix
            path: /swagger
            backend:
              service:
                name: ploutarchos
                port:
                  number: {{ .Values.envVariables.ploutarchos.port }}
